server:
  #port: ${random.int[10000,19999]}
  port: 10000
zhou:
  #114.55.92.111,10.3.17.115
  tcpHostIp:  114.55.92.111

  tcpHostPort: 1001
  isTcpSever: false
#springBoot2.0   root
logging:
  level:
    root: debug,info,error,
  